### ISSUE TITLE
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by MalazTamim** [Zeqiang-Lai/Anything2Image#13]
I got this error RuntimeError: "LayerNormKernelImpl" not implemented for 'Half' when trying to run the generate image code (images = pipe(image_embeds=embeddings.half()).images) on Google Colab. Any idea how to fix it?

**Comment by Zeqiang-Lai** [comment]
colab demo needs enable gpu
